
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ALFITO
 */
public class formpubg extends javax.swing.JFrame {
    subclass pubg = new subclass();
        int diskon, harga, tobay;

    /**
     * Creates new form formpubg
     */
    public formpubg() {
        initComponents();
         nonaktif();
        bhitung.setEnabled(false);
    }
    void aktif(){
        tid.setEnabled(true);
         cbdm.setEnabled(true);
          only.setEnabled(true);
           randm.setEnabled(true);
             rdpulsa.setEnabled(true);
             rdbca.setEnabled(true);
              rdovo.setEnabled(true);
              tdiskon.setEnabled(true);
              ttotalbayar.setEnabled(true);
              thargadm.setEnabled(true);
              tbayar.setEnabled(true);
              bbayar.setEnabled(true);
              bselesai.setEnabled(true);
              
              
    }
    void nonaktif(){
        tid.setEnabled(false);
         cbdm.setEnabled(false);
          only.setEnabled(false);
           randm.setEnabled(false);
             rdpulsa.setEnabled(false);
             rdbca.setEnabled(false);
              rdovo.setEnabled(false);
              tdiskon.setEnabled(false);
              ttotalbayar.setEnabled(false);
              thargadm.setEnabled(false);
              tbayar.setEnabled(false);
              bbayar.setEnabled(false);
              bselesai.setEnabled(false);
    }
     void bersih(){
        tid.setText("");
         cbdm.setSelectedItem("JUMLAH DIAMOND");
          bg1.clearSelection();
          bg2.clearSelection();
             thargadm.setText("");
              tdiskon.setText("");
              ttotalbayar.setText("");
               tbayar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        bg2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        cbdm = new javax.swing.JComboBox<>();
        only = new javax.swing.JCheckBox();
        randm = new javax.swing.JCheckBox();
        thargadm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txabill = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        rdpulsa = new javax.swing.JRadioButton();
        rdbca = new javax.swing.JRadioButton();
        rdovo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        tdiskon = new javax.swing.JTextField();
        bhitung = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ttotalbayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tbayar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bbaru = new javax.swing.JButton();
        bbayar = new javax.swing.JButton();
        bselesai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 255));
        jLabel1.setText("JAVA TOP UP ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel2.setText("==PUBG==");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jLabel3.setText("MASUKAN ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setText("JUMLAH DIAMOND");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setText("PAKET BELI");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel6.setText(" HARGA DIAMOND");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));
        jPanel2.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 140, -1));

        cbdm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JUMLAH DIAMOND", "99", "199", "299", "399", " " }));
        jPanel2.add(cbdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 140, -1));

        bg1.add(only);
        only.setText("HANYA DIAMOND");
        only.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlyActionPerformed(evt);
            }
        });
        jPanel2.add(only, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 140, -1));

        bg1.add(randm);
        randm.setText("RANDOM BONUS");
        randm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randmActionPerformed(evt);
            }
        });
        jPanel2.add(randm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 140, -1));
        jPanel2.add(thargadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 140, -1));

        txabill.setColumns(20);
        txabill.setRows(5);
        jScrollPane1.setViewportView(txabill);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 200, 270));

        jLabel7.setText("PEMBAYARAN");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        bg2.add(rdpulsa);
        rdpulsa.setText("PULSA");
        rdpulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdpulsaActionPerformed(evt);
            }
        });
        jPanel2.add(rdpulsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        bg2.add(rdbca);
        rdbca.setText("BCA");
        rdbca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbcaActionPerformed(evt);
            }
        });
        jPanel2.add(rdbca, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        bg2.add(rdovo);
        rdovo.setText("OVO");
        rdovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdovoActionPerformed(evt);
            }
        });
        jPanel2.add(rdovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jLabel8.setText("DISKON");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));
        jPanel2.add(tdiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 70, -1));

        bhitung.setText("HITUNG");
        bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungActionPerformed(evt);
            }
        });
        jPanel2.add(bhitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jLabel9.setText("TOTAL HARGA");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));
        jPanel2.add(ttotalbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 110, -1));

        jLabel10.setText("BAYAR");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));
        jPanel2.add(tbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 110, -1));

        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        bbaru.setText("BARU");
        bbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbaruActionPerformed(evt);
            }
        });
        jPanel2.add(bbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        bbayar.setText("BAYAR");
        bbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbayarActionPerformed(evt);
            }
        });
        jPanel2.add(bbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        bselesai.setText("SELESAI");
        bselesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bselesaiActionPerformed(evt);
            }
        });
        jPanel2.add(bselesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(814, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void onlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlyActionPerformed
        // TODO add your handling code here:
        if(cbdm.getSelectedItem().equals("99"))

        {
            thargadm.setText("65000");
        }
        else if (cbdm.getSelectedItem().equals("199"))

        {
            thargadm.setText("95000");
        }
        else if (cbdm.getSelectedItem().equals("299"))

        {
            thargadm.setText("135000");
        }
        else if (cbdm.getSelectedItem().equals("399"))

        {
            thargadm.setText("185000");
        }
        else
        {
            thargadm.setText("0");
        }
    }//GEN-LAST:event_onlyActionPerformed

    private void randmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randmActionPerformed
        // TODO add your handling code here:
        if(cbdm.getSelectedItem().equals("99"))

        {
            thargadm.setText("65000");
        }
        else if (cbdm.getSelectedItem().equals("199"))

        {
            thargadm.setText("100000");
        }
        else if (cbdm.getSelectedItem().equals("299"))

        {
            thargadm.setText("145000");
        }
        else if (cbdm.getSelectedItem().equals("399"))

        {
            thargadm.setText("195000");
        }
        else
        {
            thargadm.setText("0");
        }
    }//GEN-LAST:event_randmActionPerformed

    private void rdpulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdpulsaActionPerformed
        // TODO add your handling code here:
        pubg.setPembayaran(rdpulsa.getText());
        pubg.setSeleksiPembayaran();
        tdiskon.setText(Integer.toString(pubg.getDiskon()));
        bhitung.setEnabled(true);
    }//GEN-LAST:event_rdpulsaActionPerformed

    private void rdbcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbcaActionPerformed
        // TODO add your handling code here:
        pubg.setPembayaran(rdbca.getText());
        pubg.setSeleksiPembayaran();
        tdiskon.setText(Integer.toString(pubg.getDiskon()));
        bhitung.setEnabled(true);
    }//GEN-LAST:event_rdbcaActionPerformed

    private void rdovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdovoActionPerformed
        // TODO add your handling code here:
        pubg.setPembayaran(rdovo.getText());
        pubg.setSeleksiPembayaran();
        tdiskon.setText(Integer.toString(pubg.getDiskon()));
        bhitung.setEnabled(true);
    }//GEN-LAST:event_rdovoActionPerformed

    private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
        // TODO add your handling code here:
        harga=Integer.parseInt(thargadm .getText());
        diskon=Integer.parseInt(Integer.toString(pubg.getDiskon()));
        tobay=harga-diskon;
        ttotalbayar.setText(String.valueOf(tobay));
    }//GEN-LAST:event_bhitungActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        formhome i = new formhome();
        i.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbaruActionPerformed
        // TODO add your handling code here:
        aktif();
        bersih();
        tid.requestFocus();
    }//GEN-LAST:event_bbaruActionPerformed

    private void bbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbayarActionPerformed
        // TODO add your handling code here:
        if(thargadm.getText().isEmpty() || tid.getText().isEmpty() || ttotalbayar.getText().isEmpty() || tbayar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Harus Diisi");
        }else{
            int bayar = Integer.parseInt(tbayar.getText());
            int total = Integer.parseInt(ttotalbayar.getText());
            int kembalian = bayar-total;
            JOptionPane.showMessageDialog(null,"Kembalian Anda :\n"+kembalian );
        }

        txabill.setText
        ("ID: " + tid.getText() + "\n"
            + "Jumlah Diamond: " + cbdm.getSelectedItem().toString() + "\n"
            + "Jenis Pembayaran: " + (rdpulsa.isSelected() ? "PULSA" : rdbca.isSelected() ? "BCA" : rdovo.isSelected() ? "OVO" : "") + "\n"
            + "Harga: " + thargadm.getText() + "\n"
            + "Diskon: " + tdiskon.getText() + "\n"
            + "Total Bayar: " + ttotalbayar.getText() + "\n"
            + "Pembayaran: " + tbayar.getText() + "\n"
            + "-------------------------\n");
    }//GEN-LAST:event_bbayarActionPerformed

    private void bselesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bselesaiActionPerformed
        // TODO add your handling code here:
        int tutup;
        tutup=JOptionPane.showConfirmDialog(null,"Ingin Menutup","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (tutup==JOptionPane.YES_OPTION)
        {dispose();}
        else
        {}
    }//GEN-LAST:event_bselesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(formpubg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(formpubg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(formpubg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(formpubg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formpubg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbaru;
    private javax.swing.JButton bbayar;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.ButtonGroup bg2;
    private javax.swing.JButton bhitung;
    private javax.swing.JButton bselesai;
    private javax.swing.JComboBox<String> cbdm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox only;
    private javax.swing.JCheckBox randm;
    private javax.swing.JRadioButton rdbca;
    private javax.swing.JRadioButton rdovo;
    private javax.swing.JRadioButton rdpulsa;
    private javax.swing.JTextField tbayar;
    private javax.swing.JTextField tdiskon;
    private javax.swing.JTextField thargadm;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField ttotalbayar;
    private javax.swing.JTextArea txabill;
    // End of variables declaration//GEN-END:variables
}
