
import tiket.Tiket;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Axioo Class Program
 */
public class FormTiket extends javax.swing.JFrame {

    Tiket tkt=new Tiket();
    
    
    private double bca,bri,bni,ob,ttl,ttlp1,ttlp2,ttlp3,ttlpttl,ttlp,ttlall;
    
    
    /**
     * Creates new form FormTiket
     */
    public FormTiket() {
        initComponents();
        
        cbKode.addItem("PILIH");
        cbKode.addItem("T001");
        cbKode.addItem("T002");
        cbKode.addItem("T003");
        cbKode.addItem("T004");
        cbKode.addItem("T005");
        
        aktif();
        bersih();
        
    }
    
    void bersih(){
        nb.setText("");
        thrg.setText("");
        tjml.setText("");
        ttot.setText("");
        tubyr.setText("");
        tukemb.setText("");
        ttotpak.setText("");
        tbca.setText("");
        tbri.setText("");
        tbni.setText("");
        tob.setText("");
        ttotall.setText("");
        cbKode.setSelectedItem("PILIH");
    }
    
    void aktif(){
        cbKode.setEnabled(true);
        tjml.setEnabled(true);
        tubyr.setEnabled(true);
        tukemb.setEnabled(true);
        cb1.setEnabled(true);
        cb2.setEnabled(true);
        cb3.setEnabled(true);
        jb1.setEnabled(true);
        jb2.setEnabled(true);
        jb3.setEnabled(true);
        thrgp1.setEnabled(true);
        thrgp2.setEnabled(true);
        thrgp3.setEnabled(true);
        rbbca.setEnabled(true);
        rbbri.setEnabled(true);
        rbbni.setEnabled(true);
        rbob.setEnabled(true);
        ttotall.setEnabled(true);
    }
    
    void makanannonaktif(){
        cb1.setEnabled(false);
        cb2.setEnabled(false);
        cb3.setEnabled(false);
        jb1.setEnabled(false);
        jb2.setEnabled(false);
        jb3.setEnabled(false);
        thrgp1.setEnabled(false);
        thrgp2.setEnabled(false);
        thrgp3.setEnabled(false);
        ttotpak.setEnabled(false);
    }
    
    void paket1(){
        jb1.setEnabled(true);
        thrgp1.setEnabled(true);
    }
    
    void paket2(){
        jb2.setEnabled(true);
        thrgp2.setEnabled(true);
    }
    
    void paket3(){
        jb3.setEnabled(true);
        thrgp3.setEnabled(true);
    }
    
    void makananaktif(){
        cb1.setEnabled(true);
        cb2.setEnabled(true);
        cb3.setEnabled(true);
        jb1.setEnabled(false);
        jb2.setEnabled(false);
        jb3.setEnabled(false);
        thrgp1.setEnabled(false);
        thrgp2.setEnabled(false);
        thrgp3.setEnabled(false);
        ttotpak.setEnabled(true);
    }
    
    void nonaktif(){
        cbKode.setEnabled(false);
        nb.setEnabled(false);
        thrg.setEnabled(false);
        tjml.setEnabled(false);
        ttot.setEnabled(false);
        tubyr.setEnabled(false);
        tukemb.setEnabled(false);
        cb1.setEnabled(false);
        cb2.setEnabled(false);
        cb3.setEnabled(false);
        jb1.setEnabled(false);
        jb2.setEnabled(false);
        jb3.setEnabled(false);
        thrgp1.setEnabled(false);
        thrgp2.setEnabled(false);
        thrgp3.setEnabled(false);
        ttotpak.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        paketcemilan = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        cb1 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        cb2 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        cb3 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jb1 = new javax.swing.JTextField();
        jb2 = new javax.swing.JTextField();
        jb3 = new javax.swing.JTextField();
        thrgp1 = new javax.swing.JTextField();
        thrgp2 = new javax.swing.JTextField();
        thrgp3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ttotpak = new javax.swing.JTextField();
        bHitung = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        namapembeli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbKode = new javax.swing.JComboBox<>();
        nb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tjml = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        thrg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ttot = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tubyr = new javax.swing.JTextField();
        tukemb = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        rbbca = new javax.swing.JRadioButton();
        rbob = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        ttotall = new javax.swing.JTextField();
        tbca = new javax.swing.JTextField();
        tob = new javax.swing.JTextField();
        rbbri = new javax.swing.JRadioButton();
        tbri = new javax.swing.JTextField();
        rbbni = new javax.swing.JRadioButton();
        tbni = new javax.swing.JTextField();
        berase = new javax.swing.JButton();
        btotal = new javax.swing.JButton();
        bclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("=======================");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INDONESIA       VS      BRAZIL");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FIFA MATCHDAY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        paketcemilan.setText("Paket Cemilan");
        paketcemilan.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                paketcemilanStateChanged(evt);
            }
        });
        paketcemilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketcemilanActionPerformed(evt);
            }
        });

        jLabel12.setText("Menu Paket Cemilan :");

        cb1.setText("Paket 1");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        jLabel15.setText("(Salted Popcorn + Pocari Sweat)");

        cb2.setText("Paket 2");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        jLabel17.setText("(Sweet Popcorn + Lemon Tea)");

        cb3.setText("Paket 3");
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });

        jLabel19.setText("(Original Popcorn + Mineral Water)");

        jLabel16.setText("Rp. 60.000");

        jLabel18.setText("Rp. 45.000");

        jLabel20.setText("Rp. 20.000");

        jb1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb1KeyPressed(evt);
            }
        });

        jb2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb2KeyPressed(evt);
            }
        });

        jb3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb3KeyPressed(evt);
            }
        });

        thrgp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thrgp1ActionPerformed(evt);
            }
        });

        jLabel21.setText("Total Harga Paket :");

        ttotpak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttotpakActionPerformed(evt);
            }
        });

        bHitung.setText("Hitung");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(cb1)
                            .addComponent(cb2)
                            .addComponent(cb3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(thrgp3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thrgp2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thrgp1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel21)
                                .addGap(36, 36, 36)
                                .addComponent(ttotpak, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(bHitung))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(paketcemilan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(paketcemilan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thrgp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(cb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(thrgp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(cb3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thrgp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ttotpak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHitung))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("NAMA PEMBELI :");

        namapembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namapembeliActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("KODE TIKET :");

        cbKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKodeActionPerformed(evt);
            }
        });

        nb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("KATEGORI :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("JUMLAH BELI :");

        tjml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjmlActionPerformed(evt);
            }
        });
        tjml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tjmlKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("HARGA TIKET :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("TOTAL :");

        ttot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namapembeli)
                            .addComponent(cbKode, 0, 149, Short.MAX_VALUE)
                            .addComponent(nb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tjml))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(thrg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ttot, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(namapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tjml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(nb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setText("==============================");

        jLabel10.setText("Uang Bayar :");

        jLabel11.setText("Uang Kembali :");

        tubyr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tubyrActionPerformed(evt);
            }
        });
        tubyr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tubyrKeyPressed(evt);
            }
        });

        tukemb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tukembActionPerformed(evt);
            }
        });
        tukemb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tukembKeyPressed(evt);
            }
        });

        jLabel22.setText("Pilih Metode Pembayaran");

        buttonGroup1.add(rbbca);
        rbbca.setText("BCA");
        rbbca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbcaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbob);
        rbob.setText("Other Bank");
        rbob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbobActionPerformed(evt);
            }
        });

        jLabel23.setText("Total Pembayaran :");

        ttotall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttotallActionPerformed(evt);
            }
        });

        tbca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbcaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbbri);
        rbbri.setText("BRI");
        rbbri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbriActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbbni);
        rbbni.setText("BNI");
        rbbni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbniActionPerformed(evt);
            }
        });

        berase.setText("HAPUS");
        berase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beraseActionPerformed(evt);
            }
        });

        btotal.setText("TOTAL");
        btotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btotalActionPerformed(evt);
            }
        });

        bclose.setText("KELUAR");
        bclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tbca, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(tbri, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rbbca, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbbri, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbbni, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbni, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tob, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbob, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(berase, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bclose, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tubyr, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tukemb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(ttotall, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbbca)
                    .addComponent(rbbri))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbbni)
                    .addComponent(rbob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ttotall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tubyr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tukemb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(berase, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btotal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bclose, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tjmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjmlActionPerformed

    private void cbKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKodeActionPerformed
        // TODO add your handling code here:
        
        tkt.setKd(cbKode.getSelectedItem().toString());
        tkt.setSeleksiKd();
        nb.setText(tkt.getNm());
        thrg.setText(Double.toString(tkt.getHrg()));
        tjml.requestFocus();    
    }//GEN-LAST:event_cbKodeActionPerformed

    private void tjmlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tjmlKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tkt.setJml(Integer.parseInt(tjml.getText()));
            ttot.setText(Double.toString(tkt.getTot()));
            tubyr.grabFocus();
        }
    }//GEN-LAST:event_tjmlKeyPressed

    private void bcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcloseActionPerformed
        // TODO add your handling code here:
        int x;
        x=JOptionPane.showConfirmDialog(null,"Anda yakin mau keluar??","Konfirm",
                JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.YES_OPTION)
            dispose();
        else
            return;
    }//GEN-LAST:event_bcloseActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        
        String paket1;
        if(cb1.isSelected()){
        paket1=cb1.getText();
        tkt.setPaket1(paket1);
        tkt.getPaket1();
        }
        else{
        paket1="";
        tkt.setPaket1(paket1);
        tkt.getPaket1();
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
        
        String paket2;
        if(cb2.isSelected()){
        paket2=cb2.getText();    
        tkt.setPaket2(paket2);
        tkt.getPaket2();
        }else{
        paket2="";
        tkt.setPaket2(paket2);
        tkt.getPaket2();    
        }
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        // TODO add your handling code here:
        
        String paket3;
        if(cb3.isSelected()){
        paket3=cb3.getText();    
        tkt.setPaket3(paket3);
        tkt.getPaket3();
        }else{
        paket3="";
        tkt.setPaket3(paket3);
        tkt.getPaket3();    
        }
    }//GEN-LAST:event_cb3ActionPerformed

    private void thrgp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thrgp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thrgp1ActionPerformed

    private void jb1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tkt.setJb1(Integer.parseInt(jb1.getText()));
            thrgp1.setText(Double.toString(tkt.getTtlp1()));
            tubyr.grabFocus();
        }
    }//GEN-LAST:event_jb1KeyPressed

    private void jb2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tkt.setJb2(Integer.parseInt(jb2.getText()));
            thrgp2.setText(Double.toString(tkt.getTtlp2()));
            tubyr.grabFocus();
        }
    }//GEN-LAST:event_jb2KeyPressed

    private void jb3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tkt.setJb3(Integer.parseInt(jb3.getText()));
            thrgp3.setText(Double.toString(tkt.getTtlp3()));
            tubyr.grabFocus();
        }
    }//GEN-LAST:event_jb3KeyPressed

    private void ttotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttotActionPerformed

    private void ttotpakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttotpakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttotpakActionPerformed

    private void beraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beraseActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_beraseActionPerformed

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        // TODO add your handling code here:
        
        
        if(cb1.isSelected()){
        ttlp1 = Double.parseDouble(thrgp1.getText());
        ttlp = ttlp1;
        ttotpak.setText(Double.toString(ttlp));
        }if(cb1.isSelected()){
        ttlp2 = Double.parseDouble(thrgp2.getText());
        ttlp1 = Double.parseDouble(thrgp1.getText());
        ttlp = ttlp1+ttlp2;
        ttotpak.setText(Double.toString(ttlp)); 
        } else if(cb1.isSelected()){
         ttlp1 = Double.parseDouble(thrgp1.getText());
         ttlp2 = Double.parseDouble(thrgp2.getText());
         ttlp3 = Double.parseDouble(thrgp3.getText());
         ttlp = ttlp1+ttlp2+ttlp3; 
         ttotpak.setText(Double.toString(ttlp));
        }
            
        
            if(cb2.isSelected()){
                ttlp2 = Double.parseDouble(thrgp2.getText());
                ttlp = ttlp2;
                ttotpak.setText(Double.toString(ttlp));

            }if(cb2.isSelected()){
                    ttlp2 = Double.parseDouble(thrgp2.getText());
                    ttlp1 = Double.parseDouble(thrgp1.getText());
                    ttlp = ttlp1+ttlp2;
                    ttotpak.setText(Double.toString(ttlp));
                    }
            else if(cb2.isSelected()){
                    ttlp1 = Double.parseDouble(thrgp1.getText());
                    ttlp2 = Double.parseDouble(thrgp2.getText());
                    ttlp3 = Double.parseDouble(thrgp3.getText());
                    ttlp = ttlp1+ttlp2+ttlp3; 
                    ttotpak.setText(Double.toString(ttlp));
                    }
                        if(cb3.isSelected()){
                            ttlp3=Double.parseDouble(thrgp3.getText());
                            ttlp=ttlp3;
                            ttotpak.setText(Double.toString(ttlp));
                        }if(cb3.isSelected()){
                            ttlp1 = Double.parseDouble(thrgp1.getText());
                            ttlp3 = Double.parseDouble(thrgp3.getText());
                            ttlp = ttlp1+ttlp3;
                            ttotpak.setText(Double.toString(ttlp));
                        }if(cb3.isSelected()){
                            ttlp2 = Double.parseDouble(thrgp2.getText());
                            ttlp3 = Double.parseDouble(thrgp3.getText());
                            ttlp = ttlp2+ttlp3; 
                            ttotpak.setText(Double.toString(ttlp));
                        }
                        if(cb3.isSelected()){
                            ttlp1 = Double.parseDouble(thrgp1.getText());
                            ttlp2 = Double.parseDouble(thrgp2.getText());
                            ttlp3 = Double.parseDouble(thrgp3.getText());
                            ttlp = ttlp1+ttlp2+ttlp3; 
                            ttotpak.setText(Double.toString(ttlp));
                        }
        
      
        
    }//GEN-LAST:event_bHitungActionPerformed

    private void paketcemilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketcemilanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_paketcemilanActionPerformed

    private void paketcemilanStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_paketcemilanStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_paketcemilanStateChanged

    private void rbbcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbcaActionPerformed
        // TODO add your handling code here:
        tkt.setCara(rbbca.getText());
        tkt.setSeleksiCara();
        tbca.setText(Double.toString(tkt.getBiaya()));
        tob.setText("");
        tbri.setText("");
        tbni.setText("");
    }//GEN-LAST:event_rbbcaActionPerformed

    private void rbobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbobActionPerformed
        // TODO add your handling code here:
        tkt.setCara(rbob.getText());
        tkt.setSeleksiCara();
        tob.setText(Double.toString(tkt.getBiaya()));
        tbca.setText("");
        tbri.setText("");
        tbni.setText("");
    }//GEN-LAST:event_rbobActionPerformed

    private void tbcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbcaActionPerformed

    private void rbbriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbriActionPerformed
        // TODO add your handling code here:
        tkt.setCara(rbbri.getText());
        tkt.setSeleksiCara();
        tbri.setText(Double.toString(tkt.getBiaya()));
        tbca.setText("");
        tbni.setText("");
        tob.setText("");
    }//GEN-LAST:event_rbbriActionPerformed

    private void rbbniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbniActionPerformed
        // TODO add your handling code here:
        tkt.setCara(rbbni.getText());
        tkt.setSeleksiCara();
        tbni.setText(Double.toString(tkt.getBiaya()));
        tbri.setText("");
        tbca.setText("");
        tob.setText("");
    }//GEN-LAST:event_rbbniActionPerformed

    private void ttotallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttotallActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_ttotallActionPerformed

    private void btotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btotalActionPerformed
        // TODO add your handling code here:
        
        paketcemilan.setSelected(false);
        
        
       if(rbbca.isSelected()){
        ttl=Double.parseDouble(ttot.getText());
        ttlp=Double.parseDouble(ttotpak.getText());
        bca=Double.parseDouble(tbca.getText());
        ttlall=ttl+ttlp+bca;
        ttotall.setText(Double.toString(ttlall));
       }
       if(rbbri.isSelected()){
        ttl=Double.parseDouble(ttot.getText());
        ttlp=Double.parseDouble(ttotpak.getText());
        bri=Double.parseDouble(tbri.getText());
        ttlall=ttl+ttlp+bri;
        ttotall.setText(Double.toString(ttlall));
       }
        if(rbbni.isSelected()){
        ttl=Double.parseDouble(ttot.getText());
        ttlp=Double.parseDouble(ttotpak.getText());
        bni=Double.parseDouble(tbni.getText());
        ttlall=ttl+ttlp+bni;
        ttotall.setText(Double.toString(ttlall));
       }
         if(rbob.isSelected()){
        ttl=Double.parseDouble(ttot.getText());
        ttlp=Double.parseDouble(ttotpak.getText());
        ob=Double.parseDouble(tob.getText());
        ttlall=ttl+ttlp+ob;
        ttotall.setText(Double.toString(ttlall));
       }
      
        
    }//GEN-LAST:event_btotalActionPerformed

    private void tubyrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tubyrKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tkt.setUb(Double.parseDouble(tubyr.getText()));
            tukemb.setText(Double.toString(tkt.getUk()));
            double ttlall,ub,uk;
        
            ttlall=Double.parseDouble(ttotall.getText());
            ub=Double.parseDouble(tubyr.getText());

            uk=ub-ttlall;
            tukemb.setText(Double.toString(uk));
            if(tkt.getUb()<tkt.getTtlall()){
                JOptionPane.showMessageDialog(null,"Mohon Maaf Pembayaran Kurang",
                    "Warning",JOptionPane.OK_OPTION);
                tukemb.setText("");
                tubyr.setText("");}
            else{
                return;

            }
        }
    }//GEN-LAST:event_tubyrKeyPressed

    private void tubyrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tubyrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tubyrActionPerformed

    private void tukembActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tukembActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tukembActionPerformed

    private void tukembKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tukembKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tukembKeyPressed

    private void nbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbActionPerformed

    private void namapembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapembeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bclose;
    private javax.swing.JButton berase;
    private javax.swing.JButton btotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JComboBox<String> cbKode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jb1;
    private javax.swing.JTextField jb2;
    private javax.swing.JTextField jb3;
    private javax.swing.JTextField namapembeli;
    private javax.swing.JTextField nb;
    private javax.swing.JCheckBox paketcemilan;
    private javax.swing.JRadioButton rbbca;
    private javax.swing.JRadioButton rbbni;
    private javax.swing.JRadioButton rbbri;
    private javax.swing.JRadioButton rbob;
    private javax.swing.JTextField tbca;
    private javax.swing.JTextField tbni;
    private javax.swing.JTextField tbri;
    private javax.swing.JTextField thrg;
    private javax.swing.JTextField thrgp1;
    private javax.swing.JTextField thrgp2;
    private javax.swing.JTextField thrgp3;
    private javax.swing.JTextField tjml;
    private javax.swing.JTextField tob;
    private javax.swing.JTextField ttot;
    private javax.swing.JTextField ttotall;
    private javax.swing.JTextField ttotpak;
    private javax.swing.JTextField tubyr;
    private javax.swing.JTextField tukemb;
    // End of variables declaration//GEN-END:variables

   
}
