
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import tiket.Tiket;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fahrul
 */
public class TiketBola extends javax.swing.JFrame {

    private double bca,bri,bni,ob,ttl,ttlp1,ttlp2,ttlp3,ttlpttl,ttlp,ttlall;
    
    Tiket tkt=new Tiket();
    /**
     * Creates new form TiketBola
     */
    public TiketBola() {
        initComponents();
        
        cbKode.addItem("PILIH");
        cbKode.addItem("T001");
        cbKode.addItem("T002");
        cbKode.addItem("T003");
        cbKode.addItem("T004");
        cbKode.addItem("T005");
        
        aktif();
        bersih();
        makanannonaktif();
    }

    void bersih(){
        nb.setText("");
        thrg.setText("");
        tjml.setText("");
        ttot.setText("");
        tubyr.setText("");
        tukemb.setText("");
        ttotpak.setText("");
        tbca.setText("");
        tbri.setText("");
        tbni.setText("");
        tob.setText("");
        ttotall.setText("");
        cbKode.setSelectedItem("PILIH");
    }
    
    void aktif(){
        cbKode.setEnabled(true);
        tjml.setEnabled(true);
        tubyr.setEnabled(true);
        tukemb.setEnabled(true);
        cb1.setEnabled(true);
        cb2.setEnabled(true);
        cb3.setEnabled(true);
        jb1.setEnabled(true);
        jb2.setEnabled(true);
        jb3.setEnabled(true);
        thrgp1.setEnabled(true);
        thrgp2.setEnabled(true);
        thrgp3.setEnabled(true);
        rbbca.setEnabled(true);
        rbbri.setEnabled(true);
        rbbni.setEnabled(true);
        rbob.setEnabled(true);
        ttotall.setEnabled(true);
    }
    void makanannonaktif(){
        cb1.setEnabled(false);
        cb2.setEnabled(false);
        cb3.setEnabled(false);
        jb1.setEnabled(false);
        jb2.setEnabled(false);
        jb3.setEnabled(false);
        thrgp1.setEnabled(false);
        thrgp2.setEnabled(false);
        thrgp3.setEnabled(false);
        ttotpak.setEnabled(false);
    }
    void paket1(){
        jb1.setEnabled(true);
        thrgp1.setEnabled(true);
    }
    
    void paket2(){
        jb2.setEnabled(true);
        thrgp2.setEnabled(true);
    }
    
    void paket3(){
        jb3.setEnabled(true);
        thrgp3.setEnabled(true);
    }
    
    void makananaktif(){
        cb1.setEnabled(true);
        cb2.setEnabled(true);
        cb3.setEnabled(true);
        jb1.setEnabled(false);
        jb2.setEnabled(false);
        jb3.setEnabled(false);
        thrgp1.setEnabled(false);
        thrgp2.setEnabled(false);
        thrgp3.setEnabled(false);
        ttotpak.setEnabled(true);
    }
    
    void nonaktif(){
        cbKode.setEnabled(false);
        nb.setEnabled(false);
        thrg.setEnabled(false);
        tjml.setEnabled(false);
        ttot.setEnabled(false);
        tubyr.setEnabled(false);
        tukemb.setEnabled(false);
        cb1.setEnabled(false);
        cb2.setEnabled(false);
        cb3.setEnabled(false);
        jb1.setEnabled(false);
        jb2.setEnabled(false);
        jb3.setEnabled(false);
        thrgp1.setEnabled(false);
        thrgp2.setEnabled(false);
        thrgp3.setEnabled(false);
        ttotpak.setEnabled(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tjml = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        thrg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ttot = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        paketcemilan = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        cb1 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        cb2 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        cb3 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jb1 = new javax.swing.JTextField();
        jb2 = new javax.swing.JTextField();
        jb3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rbbca = new javax.swing.JRadioButton();
        rbbni = new javax.swing.JRadioButton();
        rbbri = new javax.swing.JRadioButton();
        tbca = new javax.swing.JTextField();
        tbni = new javax.swing.JTextField();
        rbob = new javax.swing.JRadioButton();
        tbri = new javax.swing.JTextField();
        tob = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ttotall = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tubyr = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tukemb = new javax.swing.JTextField();
        btotal = new javax.swing.JButton();
        berase = new javax.swing.JButton();
        bclose = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        ttotpak = new javax.swing.JTextField();
        bHitung = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        bcetak = new javax.swing.JButton();
        namapembeli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbKode = new javax.swing.JComboBox<>();
        thrgp1 = new javax.swing.JTextField();
        thrgp2 = new javax.swing.JTextField();
        thrgp3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1.setText("KODE TIKET");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TIKET PERTANDINGAN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INDONESIA   VS   BRAZIL");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FIFA MATCHDAY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(188, 188, 188)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel5.setText("KATEGORI");

        nb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel7.setText("JUMLAH PEMBELIAN");

        tjml.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tjml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjmlActionPerformed(evt);
            }
        });
        tjml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tjmlKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel8.setText("HARGA TIKET");

        thrg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel9.setText("TOTAL");

        ttot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ttot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttotActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        paketcemilan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        paketcemilan.setText("PAKET CEMILAN");
        paketcemilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketcemilanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("MENU PAKET CEMILAN :");

        cb1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb1.setText("PAKET 1");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel11.setText("(Salted Popcorn + Pocari Sweat)");

        cb2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb2.setText("PAKET 2");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel12.setText("(Sweet Popcorn + Lemon tea)");

        cb3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb3.setText("PAKET 3");
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel13.setText("(Original Popcorn + MIneral Water)");

        jb1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb1KeyPressed(evt);
            }
        });

        jb2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb2KeyPressed(evt);
            }
        });

        jb3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb3KeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Rp. 60.000");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Rp. 45.000");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Rp. 20.000");

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        rbbca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbbca.setForeground(new java.awt.Color(255, 255, 255));
        rbbca.setText("BCA");
        rbbca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbcaActionPerformed(evt);
            }
        });

        rbbni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbbni.setForeground(new java.awt.Color(255, 255, 255));
        rbbni.setText("BNI");
        rbbni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbniActionPerformed(evt);
            }
        });

        rbbri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbbri.setForeground(new java.awt.Color(255, 255, 255));
        rbbri.setText("BRI");
        rbbri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbriActionPerformed(evt);
            }
        });

        tbca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tbni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        rbob.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbob.setForeground(new java.awt.Color(255, 255, 255));
        rbob.setText("OTHER BANK");
        rbob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbobActionPerformed(evt);
            }
        });

        tbri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tob.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TOTAL PEMBAYARAN");

        ttotall.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("UANG BAYAR");

        tubyr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tubyr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tubyrKeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("UANG KEMBALI");

        tukemb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btotal.setText("PROSES");
        btotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btotalActionPerformed(evt);
            }
        });

        berase.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        berase.setText("BERSIH");

        bclose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bclose.setText("KELUAR");
        bclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbbca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbca, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbbni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbni, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ttotall)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rbbri, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbob))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tbri, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tob, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(berase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bclose, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tukemb)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tubyr)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbbca)
                    .addComponent(rbbni)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttotall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tubyr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbbri)
                            .addComponent(rbob))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tukemb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(berase, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bclose, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("TOTAL");

        ttotpak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        bHitung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bHitung.setText("HITUNG");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 51, 0));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("INDONESIA VS BRAZIL");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel20)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        bcetak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bcetak.setText("CETAK");
        bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel21)
                .addGap(31, 31, 31)
                .addComponent(ttotpak, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bHitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bcetak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ttotpak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHitung)
                    .addComponent(bcetak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        namapembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namapembeliActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setText("NAMA PEMBELI");

        cbKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKodeActionPerformed(evt);
            }
        });

        thrgp1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        thrgp2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        thrgp3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tjml, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ttot, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(namapembeli)
                                    .addComponent(nb))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addComponent(thrg, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbKode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(paketcemilan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jb1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(jb2)
                            .addComponent(jb3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thrgp1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(thrgp2)
                            .addComponent(thrgp3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tjml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ttot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(paketcemilan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cb1)
                                    .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(thrgp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cb2)
                                    .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(thrgp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cb3)
                                    .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(thrgp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbobActionPerformed
        // TODO add your handling code here:
        tkt.setCara(rbob.getText());
        tkt.setSeleksiCara();
        tob.setText(Double.toString(tkt.getBiaya()));
        tbca.setText("");
        tbri.setText("");
        tbni.setText("");
        
    }//GEN-LAST:event_rbobActionPerformed

    private void btotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btotalActionPerformed
        // TODO add your handling code here:
         
       if(rbbca.isSelected()){
        ttl=Double.parseDouble(ttot.getText());
        ttlp=Double.parseDouble(ttotpak.getText());
        bca=Double.parseDouble(tbca.getText());
        ttlall=ttl+ttlp+bca;
        ttotall.setText(Double.toString(ttlall));
       }
       if(rbbri.isSelected()){
        ttl=Double.parseDouble(ttot.getText());
        ttlp=Double.parseDouble(ttotpak.getText());
        bri=Double.parseDouble(tbri.getText());
        ttlall=ttl+ttlp+bri;
        ttotall.setText(Double.toString(ttlall));
       }
        if(rbbni.isSelected()){
        ttl=Double.parseDouble(ttot.getText());
        ttlp=Double.parseDouble(ttotpak.getText());
        bni=Double.parseDouble(tbni.getText());
        ttlall=ttl+ttlp+bni;
        ttotall.setText(Double.toString(ttlall));
       }
         if(rbob.isSelected()){
        ttl=Double.parseDouble(ttot.getText());
        ttlp=Double.parseDouble(ttotpak.getText());
        ob=Double.parseDouble(tob.getText());
        ttlall=ttl+ttlp+ob;
        ttotall.setText(Double.toString(ttlall));
       }
      
        
    }//GEN-LAST:event_btotalActionPerformed

    private void namapembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapembeliActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namapembeliActionPerformed

    private void cbKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKodeActionPerformed
        // TODO add your handling code here:
        tkt.setKd(cbKode.getSelectedItem().toString());
        tkt.setSeleksiKd();
        nb.setText(tkt.getNm());
        thrg.setText(Double.toString(tkt.getHrg()));
        tjml.requestFocus();    
    }//GEN-LAST:event_cbKodeActionPerformed

    private void nbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbActionPerformed

    private void ttotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttotActionPerformed

    private void tjmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjmlActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tjmlActionPerformed

    private void tjmlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tjmlKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tkt.setJml(Integer.parseInt(tjml.getText()));
            ttot.setText(Double.toString(tkt.getTot()));
            tubyr.grabFocus();
    }//GEN-LAST:event_tjmlKeyPressed
    }
    private void bcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcloseActionPerformed
        // TODO add your handling code here:
        int x;
        x=JOptionPane.showConfirmDialog(null,"Anda yakin mau keluar??","Konfirm",
                JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.YES_OPTION)
            dispose();
        else
            return;
    }//GEN-LAST:event_bcloseActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        paket1();
        String paket1;
        if(cb1.isSelected()){
        paket1=cb1.getText();
        tkt.setPaket1(paket1);
        tkt.getPaket1();
        }
        else{
        paket1="";
        tkt.setPaket1(paket1);
        tkt.getPaket1();
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
        paket2();
        String paket2;
        if(cb2.isSelected()){
        paket2=cb2.getText();    
        tkt.setPaket2(paket2);
        tkt.getPaket2();
        }else{
        paket2="";
        tkt.setPaket2(paket2);
        tkt.getPaket2();    
        }
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        // TODO add your handling code here:
        paket3();
        String paket3;
        if(cb3.isSelected()){
        paket3=cb3.getText();    
        tkt.setPaket3(paket3);
        tkt.getPaket3();
        }else{
        paket3="";
        tkt.setPaket3(paket3);
        tkt.getPaket3();    
        }
    }//GEN-LAST:event_cb3ActionPerformed

    private void jb1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tkt.setJb1(Integer.parseInt(jb1.getText()));
            thrgp1.setText(Double.toString(tkt.getTtlp1()));
            tubyr.grabFocus();
        }
    }//GEN-LAST:event_jb1KeyPressed

    private void jb2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tkt.setJb2(Integer.parseInt(jb2.getText()));
            thrgp2.setText(Double.toString(tkt.getTtlp2()));
            tubyr.grabFocus();
        }
    }//GEN-LAST:event_jb2KeyPressed

    private void jb3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb3KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tkt.setJb3(Integer.parseInt(jb3.getText()));
            thrgp3.setText(Double.toString(tkt.getTtlp3()));
            tubyr.grabFocus();
        }
    }//GEN-LAST:event_jb3KeyPressed

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        // TODO add your handling code here:
        if(cb1.isSelected()){
        ttlp1 = Double.parseDouble(thrgp1.getText());
        ttlp = ttlp1;
        ttotpak.setText(Double.toString(ttlp));
        }if(cb1.isSelected()){
        ttlp2 = Double.parseDouble(thrgp2.getText());
        ttlp1 = Double.parseDouble(thrgp1.getText());
        ttlp = ttlp1+ttlp2;
        ttotpak.setText(Double.toString(ttlp)); 
        }if (cb1.isSelected()){
        ttlp1 = Double.parseDouble(thrgp1.getText());
        ttlp3 = Double.parseDouble(thrgp3.getText());
        ttlp = ttlp1+ttlp3;
        ttotpak.setText(Double.toString(ttlp));
        } 
        else if(cb1.isSelected()){
         ttlp1 = Double.parseDouble(thrgp1.getText());
         ttlp2 = Double.parseDouble(thrgp2.getText());
         ttlp3 = Double.parseDouble(thrgp3.getText());
         ttlp = ttlp1+ttlp2+ttlp3; 
         ttotpak.setText(Double.toString(ttlp));
        }
            
        
            if(cb2.isSelected()){
                ttlp2 = Double.parseDouble(thrgp2.getText());
                ttlp = ttlp2;
                ttotpak.setText(Double.toString(ttlp));

            }if(cb2.isSelected()){
                    ttlp2 = Double.parseDouble(thrgp2.getText());
                    ttlp1 = Double.parseDouble(thrgp1.getText());
                    ttlp = ttlp1+ttlp2;
                    ttotpak.setText(Double.toString(ttlp));
                    }
            else if(cb2.isSelected()){
                    ttlp1 = Double.parseDouble(thrgp1.getText());
                    ttlp2 = Double.parseDouble(thrgp2.getText());
                    ttlp3 = Double.parseDouble(thrgp3.getText());
                    ttlp = ttlp1+ttlp2+ttlp3; 
                    ttotpak.setText(Double.toString(ttlp));
                    }
                        if(cb3.isSelected()){
                            ttlp3=Double.parseDouble(thrgp3.getText());
                            ttlp=ttlp3;
                            ttotpak.setText(Double.toString(ttlp));
                        }if(cb3.isSelected()){
                            ttlp1 = Double.parseDouble(thrgp1.getText());
                            ttlp3 = Double.parseDouble(thrgp3.getText());
                            ttlp = ttlp1+ttlp3;
                            ttotpak.setText(Double.toString(ttlp));
                        }if(cb3.isSelected()){
                            ttlp2 = Double.parseDouble(thrgp2.getText());
                            ttlp3 = Double.parseDouble(thrgp3.getText());
                            ttlp = ttlp2+ttlp3; 
                            ttotpak.setText(Double.toString(ttlp));
                        }
                        if(cb3.isSelected()){
                            ttlp1 = Double.parseDouble(thrgp1.getText());
                            ttlp2 = Double.parseDouble(thrgp2.getText());
                            ttlp3 = Double.parseDouble(thrgp3.getText());
                            ttlp = ttlp1+ttlp2+ttlp3; 
                            ttotpak.setText(Double.toString(ttlp));
                        }
    }//GEN-LAST:event_bHitungActionPerformed

    private void rbbcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbcaActionPerformed
        // TODO add your handling code here:
        tkt.setCara(rbbca.getText());
        tkt.setSeleksiCara();
        tbca.setText(Double.toString(tkt.getBiaya()));
        tob.setText("");
        tbri.setText("");
        tbni.setText("");
    }//GEN-LAST:event_rbbcaActionPerformed

    private void rbbriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbriActionPerformed
        // TODO add your handling code here:
        tkt.setCara(rbbri.getText());
        tkt.setSeleksiCara();
        tbri.setText(Double.toString(tkt.getBiaya()));
        tbca.setText("");
        tbni.setText("");
        tob.setText("");
    }//GEN-LAST:event_rbbriActionPerformed

    private void rbbniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbniActionPerformed
        // TODO add your handling code here:
        tkt.setCara(rbbni.getText());
        tkt.setSeleksiCara();
        tbni.setText(Double.toString(tkt.getBiaya()));
        tbri.setText("");
        tbca.setText("");
        tob.setText("");
    }//GEN-LAST:event_rbbniActionPerformed

    private void tubyrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tubyrKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tkt.setUb(Double.parseDouble(tubyr.getText()));
            tukemb.setText(Double.toString(tkt.getUk()));
            double ttlall,ub,uk;
        
            ttlall=Double.parseDouble(ttotall.getText());
            ub=Double.parseDouble(tubyr.getText());

            uk=ub-ttlall;
            tukemb.setText(Double.toString(uk));
            if(tkt.getUb()<tkt.getTtlall()){
                JOptionPane.showMessageDialog(null,"Mohon Maaf Pembayaran Kurang",
                    "Warning",JOptionPane.OK_OPTION);
                tukemb.setText("");
                tubyr.setText("");}
            else{
                return;

            }
        }
    }//GEN-LAST:event_tubyrKeyPressed

    private void paketcemilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketcemilanActionPerformed
        // TODO add your handling code here:
        makananaktif();
    }//GEN-LAST:event_paketcemilanActionPerformed

    private void bcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetakActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, 
        ("Nama Pembeli : " + namapembeli.getText() + "\n"
        + "Kode Tiket : " + cbKode.getSelectedItem().toString() + "\n"
        + "Kategori : " + nb.getText() + "\n"
        + "Jumlah Pembelian : " + tjml.getText() + "\n"
        + "Harga Tiket : " + thrg.getText() + "\n"
        + "Total Harga Tiket : " + ttot.getText() + "\n"
        + "Jenis Pembayaran : " + (rbbca.isSelected() ? "BCA" : rbbni.isSelected() ? "BNI" : rbbri.isSelected() ? "BRI" : rbob.isSelected() ? "Other Bank" : "") + "\n" 
         
        + "Total Harga Makanan : " + ttotpak.getText() + "\n"
               
        + "Total Pembayaran : " + ttotall.getText() + "\n"
        + "Uang Bayar : " + tubyr.getText() + "\n"
        + "Uang Kembali : " + tukemb.getText() + "\n"
        + "-------------------------\n"));
    }//GEN-LAST:event_bcetakActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiketBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiketBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiketBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiketBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiketBola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bcetak;
    private javax.swing.JButton bclose;
    private javax.swing.JButton berase;
    private javax.swing.JButton btotal;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JComboBox<String> cbKode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jb1;
    private javax.swing.JTextField jb2;
    private javax.swing.JTextField jb3;
    private javax.swing.JTextField namapembeli;
    private javax.swing.JTextField nb;
    private javax.swing.JCheckBox paketcemilan;
    private javax.swing.JRadioButton rbbca;
    private javax.swing.JRadioButton rbbni;
    private javax.swing.JRadioButton rbbri;
    private javax.swing.JRadioButton rbob;
    private javax.swing.JTextField tbca;
    private javax.swing.JTextField tbni;
    private javax.swing.JTextField tbri;
    private javax.swing.JTextField thrg;
    private javax.swing.JTextField thrgp1;
    private javax.swing.JTextField thrgp2;
    private javax.swing.JTextField thrgp3;
    private javax.swing.JTextField tjml;
    private javax.swing.JTextField tob;
    private javax.swing.JTextField ttot;
    private javax.swing.JTextField ttotall;
    private javax.swing.JTextField ttotpak;
    private javax.swing.JTextField tubyr;
    private javax.swing.JTextField tukemb;
    // End of variables declaration//GEN-END:variables
}
